server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/registration_app
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

